language: node_js
node_js: node
deploy:
  app: vendible
  provider: heroku
  api_key:
    secure: I3/ULWASAHwp9jTwCZfpv+wz890hyI8c7NLaneshhmqm7UnrU7gKG37s9qxNWQLNzo2es07onhyDXBcv+axIQUmG/YP+1q16krlub3xZDoxBYphZVmNThyGDgmtzWZCLNCRv65Y8e3TH3p9OY9+Ic5IJ6qBQdxJyAMTP95nE2b4edaWOJjv5waDToTLevy8czZ31YDh/K1tD7wxW7IbtiL2YYUNISkrIGgOSnxfddXdFPnpmirqbgU0S+dPG32Y+Ac2pm7393xXRVV1Y48FyVvUGLI4IwnlbAM59pRZxAApcxCW/6WQusY5ePrfoW3FJg2W2v03JY+RBmE44JXKriMrh1DXjgSn7eY78Guz6xvZwRhsCl30zueTKZlD4ojBLl67RXNjtM5DBW25+RifWlYG/XeFQYwuFWTZGa/VQulRD0gkTkefIuIM+0xF8LTZ6wpZeWpyJoZK29boTNA0Xjpw5XjgzTuTYhYM6rCjPct0zXsSdJMzRTSTEf2ppkvOuufSJX/bQsJJiVPjVvvPhL8mcAOQMxh27AUVd7FjvsFjLp6giWRcSmCjyIKZ9VQTWwYUlPHgrgR8euOu7s9YWYDRbmBUqf6dbJIY1RwaoroCA/kOTmcUKacHO082dbTiWtzWtnyiS5EgeqM0eDnuoquCPAn3b70ffTe1YHnhqYM0=
  app: Vendible
  on:
    repo: drerichards/Vendible
